server:
  port: 9191
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TechNovaSolutionRegistrationDB
    username: kacper
    password: kacper
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

